services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t acrylplatform/acryl_local_node_rpm .

script:
  - docker run -v .build:/build acrylplatform/acryl_local_node_rpm
  - du -h .build

notifications:
  email:
    - dima@acrylplatform.com