services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t acrylplatform/acryl_local_node_rpm .

script:
  - docker run -v $(pwd)/.build:/result/files acrylplatform/acryl_local_node_rpm

before_deploy:
  - export PKG_FILES=$(ls -d $(pwd)/.build/*.rpm)
  - echo "Found '$PKG_FILES' for release"
  - ls $(pwd)/.build/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $PKG_FILES
  skip_cleanup: true
  draft: true


notifications:
  email:
    - dima@acrylplatform.com