services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t acrylplatform/acryl_local_node_rpm .

script:
  - docker run -v /$(pwd)/.build:/result acrylplatform/acryl_local_node_rpm

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: /$(pwd)/.build/acryl-node-binary*.rpm
  skip_cleanup: true
  draft: true


notifications:
  email:
    - dima@acrylplatform.com