services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t acrylplatform/acryl_local_node_rpm .

script:
  - docker run -v /$(pwd)/.build:/result acrylplatform/acryl_local_node_rpm
  - du -h /$(pwd)/.build

notifications:
  email:
    - dima@acrylplatform.com