services:
  - docker

branches:
  only:
    - master
    - test

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl rpm


install:
  - docker build -t acrylplatform/acryl_local_node_testnet_rpm .


script:
  - docker run -v $(pwd)/.build:/result/ acrylplatform/acryl_local_node_testnet_rpm


before_deploy:
  - export PKG_FILES=$(ls -d $(pwd)/.build/files/*.rpm)
  - export PACKAGE_VERSION=$(rpm -qp --queryformat '%{VERSION}-%{RELEASE}' $PKG_FILES)
  - export CHANGELOG=$(rpm -qp --queryformat '%{CHANGELOGNAME}%{CHANGELOGTEXT}' $PKG_FILES | tr '\n' ' ')
  - echo "Found '$PKG_FILES' for release"
  - git config --local user.name "DPInvaders"
  - git config --local user.email "dima@acrylplatform.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$PACKAGE_VERSION}
  - git tag $TRAVIS_TAG

deploy:
   - provider: releases
     api_key: $GITHUB_TOKEN
     name: Acryl local node $PACKAGE_VERSION
     body: "$CHANGELOG"
     file_glob: true
     file: $PKG_FILES
     skip_cleanup: true
     on:
       branch: master
   - provider: releases
     api_key: $GITHUB_TOKEN
     name: Acryl local node testnet $PACKAGE_VERSION
     body: "$CHANGELOG"
     file_glob: true
     file: $PKG_FILES
     skip_cleanup: true
     prerelease: true
     on:
       branch: test


notifications:
  email:
    - dima@acrylplatform.com
