services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y rpm

install:
  - docker build -t acrylplatform/acryl_local_node_rpm .

script:
  - docker run -v $(pwd)/.build:/result/ acrylplatform/acryl_local_node_rpm

before_deploy:
  - export PKG_FILES=$(ls -d $(pwd)/.build/files/*.rpm)
  - export PACKAGE_VERSION=$(rpm -qp --queryformat '%{VERSION}' $PKG_FILES)
  - export CHANGELOG=$(rpm -qp --changelog $PKG_FILES | tr '\n' '\n\n')
  - echo "Found '$PKG_FILES' for release"
  - git config --local user.name "DPInvaders"
  - git config --local user.email "dima@acrylplatform.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$PACKAGE_VERSION}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: Acryl local node $PACKAGE_VERSION
  body: ""$CHANGELOG""
  file_glob: true
  file: $PKG_FILES
  skip_cleanup: true


notifications:
  email:
    - dima@acrylplatform.com
